# Generated by Django 4.2 on 2023-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('profile_add', models.TextField()),
                ('profile_email', models.EmailField(max_length=254)),
                ('profile_desc', models.TextField()),
                ('profile_image', models.ImageField(upload_to='about')),
            ],
        ),
    ]
